language: objective-c
osx_image: xcode7.3
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - brew update
  - brew install carthage || brew upgrade carthage
  - gem install xcpretty
  - carthage bootstrap --platform Mac
script:
  - set -o pipefail && xcodebuild -project HSTracker.xcodeproj -scheme HSTracker -sdk macosx clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
  - set -o pipefail && xcodebuild -project HSTracker.xcodeproj -scheme HSTracker -sdk macosx test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
