language: objective-c
osx_image: xcode7.2
before_install:
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
    - pod install
    - brew update
    - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
script: 
  - xctool clean build -workspace HSTracker.xcworkspace -scheme HSTracker -sdk macosx
  - xctool test -workspace HSTracker.xcworkspace -scheme HSTrackerTests -sdk macosx